name: dbt CI

on:
  push:
    branches: [ jpa-core-dev, main ]
  pull_request:
    branches: [ jpa-core-dev, main ]
  schedule:
    - cron: '0 */4 * * *'  # Every 4 hours (UTC)

jobs:
  dbt-run:
    runs-on: ubuntu-latest
    
    # Define environment variables for your Neon connection
    env:
      DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
      DB_USER: ${{ secrets.DB_USER }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install dbt-postgres
          dbt deps --profiles-dir .

      - name: dbt Debug
        run: dbt debug --profiles-dir .

      - name: dbt Run
        run: dbt run --profiles-dir .

      - name: dbt Test
        run: dbt test --profiles-dir .

      - name: Authenticate GutHub CLI
	env:
	  GH_TOKEN: ${{ secrets.GIST_TOKEN }}
	run: gh auth login --with-token < <(echo $GH_TOKEN)

      - name: Update Dynamic Badge
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/jpa-core-dev'
        env:
          GIST_ID: ${{ secrets.GIST_ID }}
          DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
          DB_USER: ${{ secrets.DB_USER }}
        run: |
          # 1. Install psql client
          sudo apt-get update && sudo apt-get install -y postgresql-client

          # 2. Query Neon for the count of models in the registry
          COUNT=$(psql "postgresql://$DB_USER:$DBT_PASSWORD@ep-cool-cherry-abo9in91-pooler.eu-west-2.aws.neon.tech/neondb?sslmode=require" -t -c "SELECT count(*) FROM marts.dim_models;")
          
          # 3. Clean the output
          CLEAN_COUNT=$(echo $COUNT | tr -d '[:space:]')
          
          # 4. Create the JSON payload for Shields.io
          echo "{\"schemaVersion\": 1, \"label\": \"Models in Registry\", \"message\": \"$CLEAN_COUNT\", \"color\": \"blue\"}" > dapol_stats.json
          
          # 5. Push to Gist using GitHub CLI (pre-installed on runners)
          gh gist edit $GIST_ID dapol_stats.json
