name: dbt CI

on:
  push:
    branches: [ jpa-core-dev, main ]
  pull_request:
    branches: [ jpa-core-dev, main ]

jobs:
  dbt-run:
    runs-on: ubuntu-latest
    
    # Define environment variables for your Neon connection
    env:
      DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
      DB_USER: ${{ secrets.DB_USER }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install dbt-postgres
          dbt deps --profiles-dir .

      - name: dbt Debug
        run: dbt debug --profiles-dir .

      - name: dbt Run
        run: dbt run --profiles-dir .

      - name: dbt Test
        run: dbt test --profiles-dir .