name: dbt CI
on: [push, pull_request]

jobs:
  dbt-run:
    runs-on: upbuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup dbt
        uses: dbt-labs/dbt-action@v1
        with:
          dbt-command: "dbt run --profiles-dir ."
      - name: Test dbt
        uses: dbt-labs/dbt-action@v1
        with:
          dbt-command: "dbt test --profiles-dir ."